version: '3.8'

services:
  proxy:
    build: .
    ports:
      - "7005:7005"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  ollama_data: 